version: '3.8'

services:
  # ... your existing services ...

  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
    networks:
      - default  # Same network as your apps

networks:
  default:
    name: crick12_network
    driver: bridge
